<?php

/**
 * Implements of hook_menu().
 */
function find_store_menu() {

  $items = array();
  
  // Where to buy
  $items['find-a-store'] = array(
    'title' => 'Find a store',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('find_store'),
    'file' => 'find_store.inc', 
    'type' => MENU_CALLBACK, 
    'access arguments' => array('access content'),
  );
  
  return $items;

}